### ISSUE TITLE
Missing Inputs on TX broadcast

### ISSUE THREAD

**Issue by CodersBrothers** [bitcoinjs/bitcoinjs-lib#955] opened 2017-12-09 20:53 UTC
I'm trying to send a transaction to the network with blockchain.info API and I'm getting the next Error: 

```
BitcoindException(super=com.neemre.btcdcli4j.core.BitcoindException: Error #-25: Missing inputs, code=-25)
```

Seems that this is because, after the chaos of the last days, some transaction input come from a orphan transaction or orphan block. I'm not sure if I'm true, because I'm a little bit lost. This is my conclusion after hours checking.

My question is: there are any way to filter unspents that are not be in a orphan block with this library?

I suppose that this check process not is responsabillity of this library, because require network status data, so, in this case: How can I avoid this problem or what I need to do? Some clue?

Right now, as a quick trick, I get the neccesary unspents inputs, after a random select. With this I can be lucky and take not orphan unspents.

**Comment by yuyaogawa** [comment] 2017-12-10 03:49
I have same issue here #951

**Comment by dcousens** [comment] 2017-12-10 05:45
Closing as duplicate of #951,  @CodersBrothers I've copied your question there :+1:

**Closed by dcousens** 2017-12-10 05:45 UTC
Labels: how to / question / docs
