### ISSUE TITLE
bscript.compile is not a function

### ISSUE THREAD

**Issue by WillCoco** [bitcoinjs/bitcoinjs-lib#906] opened 2017-09-25 09:25 UTC
when I try to build a new Transaction:

bscript.compile is not a function

**Comment by dcousens** [comment] 2017-09-25 10:42
Please post the code you are trying... how is `bscript` defined?

**Comment by WillCoco** [comment] 2017-09-26 02:13
bitcoinjs-lib works well with node.js
I try bitcoinjs-lib  with RN & [nodeify](https://github.com/mvayngrib/rn-nodeify), it dose not work.I think it's a question of nodeify

**Comment by dcousens** [comment] 2017-09-26 02:38
Duplicate of https://github.com/bitcoinjs/bitcoinjs-lib/issues/905#issuecomment-332064201

**Closed by dcousens** 2017-09-26 02:38 UTC
Labels: how to / question / docs
