### ISSUE TITLE
What would be the code to create and spend the script in the Mastering Bitcoin book

### ISSUE THREAD

**Issue by educob** [bitcoinjs/bitcoinjs-lib#1184] opened 2018-08-21 12:43 UTC
Hi. 
The bitcoinjs-lib example on complex scripts doesn't include multisignature.
So I am not sure how to create and spend the script in the book Mastering Bitcoin.

This is the script: 
http://tinypic.com/m/jzidy8/3

Thanks.

**Comment by dabura667** [comment] 2018-08-21 13:57
Try it.

Get it as close as you think you can and post your code.

**Comment by educob** [comment] 2018-08-21 14:51
Script creation & address: 
`
redeemScript = bitcoin.script.compile([
   bitcoin.opcodes.OP_IF,
      bitcoin.opcodes.OP_IF,
         bitcoin.opcodes.OP_2,
      bitcoin.opcodes.OP_ELSE,
         bitcoin.script.number.encode(lockTime30days),
         bitcoin.opcodes.OP_CHECKLOCKTIMEVERIFY,
         bitcoin.opcodes.OP_DROP,
         abdul.publicKey,
         bitcoin.opcodes.OP_CHECKSIGVERIFY
         bitcoin.opcodes.OP_1,
      bitcoin.opcodes.OP_ENDIF,
      mohamed.publicKey,
      saeed.publicKey,
      zaira..publicKey,
      bitcoin.opcodes.OP_3,
      bitcoin.opcodes.OP_CHECKMULTISIG,
   bitcoin.opcodes.OP_ELSE,
      bitcoin.script.number.encode(lockTime90days),
      bitcoin.opcodes.OP_CHECKLOCKTIMEVERIFY,
      bitcoin.opcodes.OP_DROP,
      abdul.publicKey,
      bitcoin.opcodes.OP_CHECKSIGVERIFY
   bitcoin.opcodes.OP_ENDIF,
])
 const { address } = bitcoin.payments.p2sh({ redeem: { output: redeemScript, network: regtest }, network: regtest })
`
Spending using path: true, true: 2 + multisginature
`
const txb = new bitcoin.TransactionBuilder(regtest)
txb.addInput(unspent.txId, unspent.vout, 0xffffffff) // not sure about this 0xffffffff
txb.addOutput(regtestUtils.RANDOM_ADDRESS, 7e4)
const tx = txb.buildIncomplete()
const signatureHash = tx.hashForSignature(0, redeemScript, hashType)
const redeemScriptSig = bitcoin.payments.p2sh({
   redeem: {
      input: bitcoin.script.compile([
         bitcoin.script.signature.encode(mohamed.sign(signatureHash), hashType), // some missing before?
         bitcoin.script.signature.encode(zaira.sign(signatureHash), hashType), // something missing after?
         bitcoin.opcodes.OP_TRUE
         bitcoin.opcodes.OP_TRUE
      ]),
       output: redeemScript
     }
}).input
tx.setInputScript(0, redeemScriptSig)
`

Spending using path: 30days, abdul sign, 1, multisginature
`
const txb = new bitcoin.TransactionBuilder(regtest)
txb.setLockTime(lockTime)
txb.addInput(unspent.txId, unspent.vout, 0xffffffff) // not sure about this 0xffffffff
txb.addOutput(regtestUtils.RANDOM_ADDRESS, 7e4)
const tx = txb.buildIncomplete()
const signatureHash = tx.hashForSignature(0, redeemScript, hashType)
const redeemScriptSig = bitcoin.payments.p2sh({
   redeem: {
      input: bitcoin.script.compile([
         bitcoin.script.signature.encode(zaira.sign(signatureHash), hashType), // something missing after?
         bitcoin.opcodes.OP_TRUE
         bitcoin.opcodes.OP_TRUE
      ]),
       output: redeemScript
     }
}).input
tx.setInputScript(0, redeemScriptSig)
`

What I really know, and I very much appreciated the help here, would be the code to have the transaction signed by the different people at different times (as opposed here all at the seame time).
Is ii possible to save the ourput of  "bitcoin.script.signature.encode(zaira.sign(signatureHash), hashType)" to be used later on?

Thanks.

**Comment by afk11** [comment] 2018-08-21 18:55
That's an awesome example! To be honest, this is hard to write in a way that's generalized to all scripts. 

For one or two scripts, you could work out in advance who needs to sign under each path, and what else is required. 

Your definition could look like the following, and based off the instruction type you know what public keys to consider validating against. 

    [true, true] 
    - Multisig(2,3, [mohamed, saeed, zaira]), count 2 stack values, not forgetting to add the OP_0 later
    - Conditional(1) (marker for 2nd path step, true)
    - Conditional(0) (marker for 1st path step, true)

    [true, false] 
    - CLTV(30 days) (nothing required on the stack for this, just the right locktime)
    - Checksig(abdul) 
    - Multisig(2,3, [mohamed, saeed, zaira])
    - Conditional(1) (marker for 2nd path step, false)
    - Conditional(0) (marker for 1st path step, true)

    [false] 
    - CLTV(90 days) (nothing required on the stack for this, just the right locktime)
    - Checksig(abdul)

For saving the signature while other people sign, you can just encode it along with other data about the input until the transaction is fully complete.

{
    tx: '',
    inputs: [
        {value: 10000000, scriptPubKey: 'xyz...', partialStack: [], path: [true, false]},
    ]
}

So you take your transaction, and over each input, check the script is an acceptable template, and the path is part of the definition. The software can then parse out the data elements from the script (the pubkeys to sign), and see if there's anything in the partialStack. It's contents are defined by the path, so you can positionally assign signatures to a checksig operation, etc.

You can compute the signature hash and validate that the signature is correct for that step (ie, not a key from another branch). If it's CLTV, check the locktime is correct. Next you just iterate over instructions, and if you own any of the keys present, sign with it. 

Good luck!

**Comment by educob** [comment] 2018-08-21 21:31
Hi afk11. Thanks for the detailed answer.

But I am lost with the functions you use: Multisig, Checksig, Conditional & CLTV.
Those functions are not in bitcoinjs-lib. Are they? Or is it pseudo-code? Is it another library?

I am struggling with the libraries as there is no documentation and just a single example.

I have developed a code that let you choose the execution path and recovers the elements in it.
But I don't know the exact code to create the transaction.

Could you adapt my code so it runs path: true true?

Any source of information so I can learn more in detail how to construct txs por these complex scripts?

Thank you for your help.

**Comment by afk11** [comment] 2018-08-22 00:49
Sorry if those weren't clear, they're not functions, more just pseudocode.. think of them as constructors for objects in the whatever pathway.

Pathway 1 [true, true] has the 2 of 3 Multisig (defining m/n/keys). We also mention the conditionals to tell our software where the true / falses get pushed. 
Pathway 2 also has a multisig, but here it was 1of3. Plus the CLTV part, because it's in the [true, false] pathway.

The objects should contain at the very least, the pubkeys and timestamps from your checksig/checkmultisig/cltv opcodes in the script (you can extract using a template!)

later, you will want the software to add signatures to these objects, so it can be encoded as a partial signature and passed to the next person.

**Comment by junderw** [comment] 2018-08-22 01:56
I'll try adding an example test case today.

**Comment by junderw** [comment] 2018-08-22 03:32
Currently the regtest server is down (cert expired) so I can't test if this works... but I think this would work.

https://github.com/bitcoinjs/bitcoinjs-lib/commit/ce60e72cd41ff26b8b59ca1a458e9a9245ce1dd1

I will make a pull request to add this example once I can verify it works.

Also, you showed `OP_CHECKLOCKTIMEVERIFY` which is an absolute locktime. (aka, lock until Next tuesday) Where `OP_CHECKSEQUENCEVERIFY` is a relative locktime (aka, lock this UTXO for "5 days" after it is confirmed, or "500 blocks" after it has confirmed. You can set this time in blocks or time (in multiples of 512 seconds))

**Comment by educob** [comment] 2018-08-22 06:05
Thanks.

I will take a close look at the code.
What a pity about the regtest.

**Comment by junderw** [comment] 2018-08-22 08:10
@educob I just tested it with `NODE_TLS_REJECT_UNAUTHORIZED=0` and it passed.

You can see my pull request here: #1185

**Comment by educob** [comment] 2018-08-22 08:20
Thank you very much. You have been most helpful.

Though I don't know what NODE_TLS_REJECT_UNAUTHORIZED means.

**Comment by junderw** [comment] 2018-08-22 08:38
> Does the regtest server works again?

No, it's still broken. The TLS cert is expired.

But if you run your process with the `NODE_TLS_REJECT_UNAUTHORIZED=0` environment variable set Node will ignore TLS errors, and it will work.

**Comment by dcousens** [comment] 2018-09-04 04:41
Closing in favour of #1185

**Closed** 2018-09-07 01:48 UTC
Labels: how to / question / docs
