### ISSUE TITLE
Invalid transaction builder output section

### ISSUE THREAD

**Issue by smdmitry** [bitcoinjs/bitcoinjs-lib#1166] opened 2018-08-08 12:50 UTC
I am using bitcoinjs-lib@4.0.1 with Vue,js in browser (Chrome, Firefox) and trying to build transaction.

The following sample code: [create a 1-to-1 Transaction](https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/transactions.js#L13)

Returns this transaction hex: `01000000019d344070eac3fe6e394a16d06d7704a7d5c0a10eb2a2c16bc98842b7cc20d561000000006d00483045022100c766a1ed287200afceaa6895e24c7e75369500be34ecf2a0c6f584e643a28e46022050a43b8fb6726397422521646df07197d4360ea09c6d66c9d6e389d51701cbfb010021029f50f51d63b345039a290c94bffd3180c99ed659ff6ea6b1242bca47eb93b59fffffffff01e02e0000000000001a0000001406afd46bcdfd22ef94ac122aa11f241244a37ecc000000000000`

Which has [invalid outputs format](https://live.blockcypher.com/btc/decodetx/). And is not equal to sample transaction builder result.

Is this a bug in bitcoinjs-lib code, or something wrong with my environment?

**Comment by junderw** [comment] 2018-08-08 14:13
Show us your code.

looking at your output it says:

```
e02e000000000000 // sending 0.00012 btc
1a // scriptPubkey is 26 bytes long
0000001406afd46bcdfd22ef94ac122aa11f241244a37ecc0000
OP_0 OP_0 OP_0 <PUSH: 06afd46bcdfd22ef94ac122aa11f241244a37ecc> OP_0 OP_0
```

Also your input has OP_0 before and after the signature, but then pushes a public key instead of a multisig redeemscript. (we use OP_0 as placeholders for incomplete multisig transactions) but you said you were trying to do a 1-to-1 transaction.

So show us the code, as I have no clue how it could get THIS messed up.

**Comment by dabura667** [comment] 2018-08-08 15:01
Ok, definitely a problem with how Vue,js packages everything.

**Comment by smdmitry** [comment] 2018-08-08 16:09
It appears that you broke something from version 3.3.2.
4.0.1 version does not run on runkit: https://npm.runkit.com/bitcoinjs-lib
But 3.3.2 version runs ok and produces expected transaction.

**Comment by dabura667** [comment] 2018-08-09 00:45
> you broke something

write a test that breaks and we'll look into it.

we support node v6 v8 v9 v10
all the tests pass.

**Comment by dcousens** [comment] 2018-08-09 01:06
@smdmitry if you could please provide a method for us to reproduce this error,  that would help us resolve your problem for the benefit of everyone :)

**Comment by junderw** [comment] 2018-08-09 02:42
> 4.0.1 version does not run on runkit

This is a problem with npm, they don't have tiny-secp256k1 installed. I reported it. This is not a problem with this library.

**Comment by dcousens** [comment] 2018-08-09 03:02
@junderw what is it doing instead though?

`.sign` should explode. 
`.build` should explode.

Why isn't it exploding with exceptions,  instead making this malformed abomination of a transaction.

Repro please!

**Comment by junderw** [comment] 2018-08-09 08:53
@dcousens it's not doing anything. It's exploding. So nothing is showing up in console.log.

I think OP is saying "runkit is broken" as a separate issue besides this Vue.JS problem.

I have never used vue.js........ so I don't know how to reproduce the error.

**Comment by djstanton** [comment] 2018-08-10 21:14
hi all, i'm posted [here](https://github.com/djstanton/bitcoinjs-lib) code  with invalid transaction hex, 
I hope this helps.

**Comment by dcousens** [comment] 2018-09-03 07:04
Do we close?  Or is there something we can action here?

**Comment by junderw** [comment] 2018-09-03 07:40
@smdmitry please help with reproduction.

**Comment by junderw** [comment] 2018-09-03 07:43
@smdmitry the runkit issue is unrelated to your issue, and is easily resolved by telling npm to install tiny-secp256k1

Please tell us how to use vue.js? How to use the code example you gave us?

Give us a link to a project and a list of steps on how to reproduce the error.

**Comment by dcousens** [comment] 2018-09-04 04:40
Will re open if needed.

**Closed** 2018-09-04 04:40 UTC
Labels: how to / question / docs

**Comment by djstanton** [comment] 2018-09-04 07:56
@dcousens @junderw, thanks, problem solved. 
Bitcoin-ops package package uses a json file. Our webpack config used file-loader.

`{
        test: /\.(png|woff|woff2|eot|ttf|jpg|gif|svg|**json**)$/,
        loader: 'file-loader',
        options: {
          name: '[name].[ext]?[hash]'
        }
 }`

and in this line  `var OPS = require('./index.json')` file-loader returned path to file, not its contents.
In the future, if we need to use json files, there will be problems again.
Maybe all the same the OPS constans are to be moved to map.js, then people will not depend on their loaders?

**Comment by dcousens** [comment] 2018-09-04 08:01
@djstanton requiring JSON files is common... if you don't support it,  you will probably be burnt by other dependencies.
I'd resolve the cause not the symptom.
Personally.

**Comment by djstanton** [comment] 2018-09-04 08:04
@dcousens on this time we removed json from flie-loader, thanks.

**Comment by junderw** [comment] 2018-09-04 08:16
wow....... vue.js devs didn't think supporting requiring json files was necessary.............

Just wow....

Every day a new NodeJS based framework comes, and every day they somehow mess everything up for their users...

so sad...
