### ISSUE TITLE
typeforce 1.5.1 breaks bitcoinjs-lib 1.5.8

### ISSUE THREAD

**Issue by williamcotton** [bitcoinjs/bitcoinjs-lib#494] opened 2015-11-05 15:19 UTC
Please see: https://github.com/dcousens/typeforce/issues/17

**Comment by jprichardson** [comment] 2015-11-05 15:38
Related: https://github.com/bitcoinjs/bitcoinjs-lib/pull/493

**Comment by dcousens** [comment] 2015-11-05 19:36
Duplicate of #493

**Closed by dcousens** 2015-11-05 19:36 UTC
