### ISSUE TITLE
tx Information

### ISSUE THREAD

**Issue by nikoliveira** [bitcoinjs/bitcoinjs-lib#776] opened 2017-04-01 04:39 UTC
How can I with api consult information like these: (in, out, balance, confirmations ..) ?

https://blockchain.info/address/196waC5nNfbF9Bho9Suy9e8QFkNciW6m1p

**Comment by dcousens** [comment] 2017-04-01 04:47
Closing as duplicate of https://github.com/bitcoinjs/bitcoinjs-lib/issues/678

**Closed by dcousens** 2017-04-01 04:47 UTC
Labels: how to / question / docs
