### ISSUE TITLE
typeError: Argument must be a Buffer

### ISSUE THREAD

**Issue by divyangkhatri** [bitcoinjs/bitcoinjs-lib#2005] opened 2023-11-18 06:19 UTC
Hello, 
I am getting following error while signing the input for Taproot.
"typeError: Argument must be a Buffer". I like to inform that other BTC type is working like segwit, native segwit, legacy.

ENV:
"react-native": "^0.71.7",
"bitcoinjs-lib": "^6.1.5"

Following is my code snippet.

```
const getTransactionFees = async ({
  fromAddress,
  amount,
  toAddress,
  privateKey,
  chain_name,
}) => {
  // Get all utxos from sender using Mempool API.
  const {data: utxos} = await BitcoinMempool.getBitcoinUTXO(fromAddress);
  const value = new BigNumber(amount);

  const ECPair = ECPairFactory(ecc);
  const keyPair = ECPair.fromWIF(privateKey, config.BITCOIN_NETWORK_STRING);
  
  //Below commented code verify that private key is proper and address is same equal to fromAddress
  // const {address} = bitcoin.payments.p2tr({
   // internalPubkey: toXOnly(keyPair.publicKey),
  //  network: config.BITCOIN_NETWORK_STRING,
  // });
 // console.log('adddress', address);
 
   // Only use the required utxos
  const [usedUTXOs, sum] = utxos.reduce(
    ([utxoAcc, total], utxo) =>
      total.lt(value)
        ? [[...utxoAcc, utxo], total.plus(utxo.value)]
        : [utxoAcc, total],
    [[], new BigNumber(0)],
  );
 // here network is testnet
  const tx = new bitcoin.Psbt({network: config.BITCOIN_NETWORK_STRING});
 
  const fetchTransactionData = usedUTXOs.map(item => ({
    txid: item.txid,
    value: item.value,
    fromAddress,
    vout: item.vout,
  }));

  const childNodeXOnlyPubkey = toXOnly(keyPair.publicKey);
  console.log('childNodeXOnlyPubkey', childNodeXOnlyPubkey); // get valid buffer
 // fetching more details of transaction from transactionId
  const resp = await BitcoinMempool.fetchTransactionDetails(
    fetchTransactionData,
  );
  const inputData = resp?.data;
  console.log('Inpute data', inputData); // here also getting proper input data nothing is undefined or null
  inputData.map(utxo => {
    if (utxo.scriptpubkey) {
      const tempInputData = {
        hash: utxo.txid,
        index: utxo.vout,
        witnessUtxo: {
          // eslint-disable-next-line no-undef
          script: Buffer.from(utxo.scriptpubkey, 'hex'),
          value: utxo.value, // value in satoshi
        },
      };
      console.log('UTXOSS', utxo);
      console.log('chain_name', chain_name);

      if (chain_name === 'bitcoin_taproot') {
        tempInputData.tapInternalKey = childNodeXOnlyPubkey;
      }
      console.log('tempss', tempInputData); // here also the proper data
      tx.addInput(tempInputData);
    } else if (utxo.txhash) {
      // this else if part is not executing
      const tempInputData = {
        hash: utxo.txid,
        index: utxo.vout,
        // eslint-disable-next-line no-undef
        nonWitnessUtxo: Buffer.from(utxo.txhash, 'hex'),
      };
      tx.addInput(tempInputData);
    }
  });
  const change = sum.minus(value);
  // Add outputs
  tx.addOutput({
    address: toAddress,
    value: value.toNumber(),
  });
  if (change.gt(0)) {
    tx.addOutput({
      address: fromAddress,
      value: change.toNumber(),
    });
  }
  console.log('txxx', tx); // getting this log also
  // Sign inputs
  for (let i = 0; i < inputData.length; i++) {
    if (chain_name === 'bitcoin_taproot') {
      const tweakedChildNode = keyPair.tweak(
        bitcoin.crypto.taggedHash('TapTweak', childNodeXOnlyPubkey),
      );
      console.log('twaieee', tweakedChildNode); // getting this log also
      await tx.signInput(i, tweakedChildNode); // here i am facing above mention error
    } else {
      await tx.signInput(i, keyPair);
    }
  }
  console.log('signed input'); // this log is not executing because above line have error
  tx.finalizeAllInputs();
  console.log('finalize');
  const createdTx = tx.extractTransaction();
  const virtualSize = createdTx.virtualSize();
  const feeRate = await BitcoinMempool.fetchTransactionFees();
  const feeRateNumber = validateNumber(feeRate?.data) || 20;
  return Math.round(feeRateNumber * virtualSize);
};

```

**Comment by divyangkhatri** [comment] 2023-11-24 06:38
@junderw Can you please checkout this issues?

**Comment by junderw** [comment] 2023-11-24 06:52
This is not enough information.

Please post a minimal reproduction case that I can run.

Pasting a huge blob of code that I can't run locally and pointing to something that throws the error will only help if the problem is a dumb mistake or obvious problem. This is not that.

So I need to be able to run it locally, but all I have are our test suite examples... which all work perfectly.

Posting a full stack trace might help to pinpoint exactly where the problem is.

Taking a stab in the dark, have you run initEccLib after importing bitcoinjs-lib?

**Comment by jasonandjay** [comment] 2024-08-26 12:06
It looks like this question has no follow-up, let's close it

**Closed by jasonandjay** 2024-08-26 12:06 UTC

**Comment by coderkhalide** [comment] 2025-01-05 08:28
@divyangkhatri how did you solved it?

**Comment by coderkhalide** [comment] 2025-01-05 10:15
This worked for me:

@junderw am i did right?

I am doing on React-Native

```
import * as bitcoin from 'bitcoinjs-lib'; // 6.1.7
import { SignerAsync, ECPairInterface, ECPairFactory, ECPairAPI } from 'ecpair'; // 3.0.0-rc.0
import * as ecc from '@bitcoinerlab/secp256k1';  // 1.2.0
import { Buffer } from 'buffer';

// Initialize the elliptic curve library
const ECPair = ECPairFactory(ecc) as ECPairAPI;

// Initialize the elliptic curve library
bitcoin.initEccLib(ecc);
const bip32 = BIP32Factory(ecc);
```

```
    /**
     * Create a transaction
     * @param {SatsUtxo[]} utxos
     * @param {string} to
     * @param {number} amount in sats
     * @param {number} feePerVByte
     * @returns {Promise<string>}
     */
    async createTransaction(utxos: SatsUtxo[], to: string, amount: number, feePerVByte: number): Promise<TransactionOutput> {
        console.log(`[BitcoinWallet] createTransaction: ${utxos.length}, ${to}, ${amount}, ${feePerVByte}`);
        return new Promise(async (resolve, reject) => {
            try {
                let totalInputValue = 0;
                let outputCount = 2

                // set mainnet
                const network = bitcoin.networks.bitcoin;

                // create keypair
                const keyPair = ECPair.fromWIF(this._private_key, network) as ECPairInterface;

                // create transaction
                const psbt = new bitcoin.Psbt({ network });

                // add inputs
                for (const utxo of utxos) {
                    totalInputValue += utxo.value;
                    if (isSegWit(utxo.script_pubkey)) {
                        psbt.addInput({
                            hash: utxo.txid,
                            index: utxo.vout,
                            witnessUtxo: {
                                script: Buffer.from(utxo.script_pubkey, "hex"),
                                value: utxo.value
                            }
                        })
                    } else {
                        // Get raw transaction
                        const raw = await fetchRawTransactionMempool(utxo.txid);

                        if (!raw) return reject(new Error('Error fetching raw transaction'));

                        psbt.addInput({
                            hash: utxo.txid,
                            index: utxo.vout,
                            nonWitnessUtxo: Buffer.from(raw, 'hex')
                        })
                    }
                }

                // Estimate transaction size and fee
                const estimatedSize = 10 + (180 * utxos.length) + 34 * outputCount - utxos.length;
                const totalFee = feePerVByte * estimatedSize
                const totalCost = amount + totalFee;

                // Check if there are enough funds for amount and fee
                if (totalInputValue < totalCost) {
                    return reject(new Error('Insufficient funds for amount and fee'));
                }

                // add outputs
                psbt.addOutput({
                    address: to,
                    value: amount,
                });

                // add change output
                if (totalInputValue > totalCost) {
                    psbt.addOutput({
                        address: this.address,
                        value: totalInputValue - totalCost,
                    });
                }

                // Signer
                const Signer = {
                    sign: async (hash: Uint8Array): Promise<Uint8Array> => {
                        return Buffer.from(keyPair.sign(hash));
                    },
                    publicKey: Buffer.from(keyPair.publicKey)
                } as SignerAsync;

                // Sign all inputs
                for (let i = 0; i < utxos.length; i++) {
                    try {
                        // @ts-ignore
                        await psbt.signInputAsync(i, Signer);
                    } catch (err) {
                        console.error(`Error signing input ${i}:`, err);
                        throw err;
                    }
                }

                // finalize the transaction
                psbt.finalizeAllInputs();

                // Get the raw transaction
                const rawTx = psbt.extractTransaction().toHex();

                // Get transaction id
                const txId = psbt.extractTransaction().getId();

                resolve({ rawHex: rawTx, txId: txId });

            } catch (error) {
                console.debug(`[BitcoinWallet] createTransaction error: `, error);
                reject(error);
            }
        });
    }
```

`isSegWit`

```
/**
 * Checks if the given scriptPubKey corresponds to a SegWit (Native or Taproot) script.
 * @param {string} scriptPubKey - The scriptPubKey in hex format.
 * @returns {boolean} True if the scriptPubKey is SegWit, otherwise false.
 */
export function isSegWit(scriptPubKey: string): boolean {
  // Convert scriptPubKey to a Buffer
  const script = Buffer.from(scriptPubKey, "hex");

  // Ensure the script length is at least 2 bytes to avoid out-of-bounds errors
  if (script.length < 2) {
    return false;
  }

  // Check for SegWit version 0 (P2WPKH or P2WSH)
  if (script[0] === 0x00 && (script[1] === 0x14 || script[1] === 0x20)) {
    console.log("🚀 ~ isSegWit ~ Detected SegWit v0 script (P2WPKH or P2WSH)");
    return true; // P2WPKH (20 bytes) or P2WSH (32 bytes)
  }

  // Check for SegWit version 1 (Taproot)
  if (script[0] === 0x01 && script[1] === 0x20) {
    console.log("🚀 ~ isSegWit ~ Detected SegWit v1 script (P2TR - Taproot)");
    return true; // P2TR (32 bytes)
  }

  console.log("🚀 ~ isSegWit ~ Not a SegWit script");
  return false;
}
```
