### ISSUE TITLE
Hash name for ripemd160 is changed for LibreSSL

### ISSUE THREAD

**Issue by liangzan** [bitcoinjs/bitcoinjs-lib#1363] opened 2019-03-19 06:16 UTC
Node.js's crypto module is dependent on the version of OpenSSL on the platform. On OSX, it has switched to LibreSSL which has a different name for ripemd160. It changed from `rmd160` to `ripemd160`, and it affects line https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/crypto.js#L4.

**Comment by junderw** [comment] 2019-03-19 06:38
It looks like this part would need to be modified to account for both patterns. Please look into writing a pull request here:

https://github.com/crypto-browserify/createHash/blob/master/index.js

Once it is merged upstream we will consider updating the dependency.

**Comment by junderw** [comment] 2019-03-19 07:43
LibreSSL 2.6.5 was able to work perfectly fine on the latest Macbook.

Can you provide repro steps for your problem?

I can not reproduce.

**Comment by junderw** [comment] 2019-03-19 08:44
Please try using a more recent version of node:

It looks like crypto.createHash in more recent versions of node has rmd160 and ripemd160 both work. The only explanation would be that your node version is old.

Closing this issue.

```
$ node -v
v10.15.3
$ npm -v
6.9.0
```

**Closed by junderw** 2019-03-19 08:44 UTC
