### ISSUE TITLE
How to send & receive bitcoin using bitcoinjs-lib?

### ISSUE THREAD

**Issue by MonarthS** [bitcoinjs/bitcoinjs-lib#1434] opened 2019-07-15 04:57 UTC
First I create HD Wallet using **BIP32** using mnemonics.

Now I want to generate new child addresses with private key using xpub & xpriv for every receive.

Then for example, I received BTC in 2 child addresses, i.e. 1 BTC & 2 BTC.

Now, I have to send 3 BTC to someone, then How can I send it as I have 3 BTC but in separate account with **utxo**.

How can I manage these accounts & transaction, and also how can I show the total balance to the user?

I thing it is insufficient to call the api to get balance for all accounts, as for HD wallet user can have thousands of addresses.

So, I understood this theoretically, but don't know how to implement this using **bitcoinjs-lib, BIP32, HD-key**.

**Comment by junderw** [comment] 2019-07-15 06:17
> call the api

Why is this insufficient? Which API are you using?

**Comment by MonarthS** [comment] 2019-07-15 06:50
Assume that there is a HD wallet, in which I received BTC in first 3 child accounts, How can I get total balance of the Wallet? I've to call the api for 3 times and also I don't know that which child account has balance and which has not. 

I'm using Bitpay insight api.

**Comment by junderw** [comment] 2019-07-15 10:24
Insight doesn't support HD, but you can query 20 addresses in one call.

Use that.

**Comment by MonarthS** [comment] 2019-07-15 13:22
Here api doesn't matter, please read my question again, I want code for sending & receiving derived addresses, and how to derive addresses with private key.

**Comment by junderw** [comment] 2019-07-15 15:56
https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/bip32.js

and

https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/transactions.js

are good places to start reading.

They are linked in the README

**Comment by MonarthS** [comment] 2019-07-16 04:21
I am using this:

```
const path = "m/0'/0/0"
const mnemonic = 'word word word word word word word word word word word word'
const seed = bip39.mnemonicToSeed(mnemonic)
const root = bip32.fromSeed(seed)

const child1 = root.derivePath("m/0'/0")
const child2 = root.derivePath("m/0'/1")

const child1Address = bitcoin.payments.p2pkh({ pubkey: child1.publicKey }).address
const child2Address = bitcoin.payments.p2pkh({ pubkey: child2.publicKey }).address
```

can I get privatekey of child addresses? If yes, then how?

**Comment by junderw** [comment] 2019-07-16 07:21
`child1.privateKey` is the private key.

**Comment by supertestnet** [comment] 2021-08-21 19:53
> https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/bip32.js
> 
> and
> 
> https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/transactions.js
> 
> are good places to start reading.
> 
> They are linked in the README

I believe the links have changed, I think the corresponding links are:

https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/bip32.spec.ts

and

https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/transactions.spec.ts

I am trying to use the createPayment() function which is inside https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/transactions.spec.ts and I am trying to do so in a browser context. The readme says that for use in the browser you need to use browserify and it links [here](https://bitcoincore.tech/apps/bitcoinjs-ui/index.html) for a web ui example of a project that uses bitcoinjs-lib. I went there to grab the browserified bitcoinjs-lib and got it [here](https://bitcoincore.tech/apps/bitcoinjs-ui/lib/bitcoinjs-lib.js), but the createPayment() function does not seem to be in that file.

I tried adding it manually in a new <script> tag but I got error messages in my console about the colons and other syntax that is not recognized in vanilla js. How do I use the createPayment() function in a browser?

What I'm really trying to make, btw, is a function which -- as input -- takes a private key, a transaction id, an integer (to specify a specific output of the transaction id), an amount (representing the amount of that output), 80 bytes of hex (for an op_return), a feerate (in sats per byte), a change address, and anything else necessary to construct the function's output, which should be: a signed transaction which, if broadcast and confirmed, will put the 80 bytes of hex into the blockchain and send the remaining change (minus a fee) to the change address.

**Comment by junderw** [comment] 2021-08-21 23:54
> I am trying to use the createPayment() function

You really shouldn't. That function is only meant to be a helper function for tests, and is not made with security in mind.

You can definitely look at it to give you ideas on how to create your own secure helper functions or classes.

> I went there to grab the browserified bitcoinjs-lib

Do not download browser bundles you find lying around on the internet. Do not trust me. Do not trust anyone. I was on the fence about adding a link to that great project because I was afraid people would do exactly what you just did; trust the person who made it and download their browser bundle blindly.

> I got error messages in my console about the colons and other syntax that is not recognized in vanilla js.

TypeScript is not Javascript. However, if you delete all the type annotation key words and type assertion characters, it will become valid Javascript.

---

Also, since the original OP was unrelated to the title, and they haven't responded in 2 years I'm closing this.

**Closed by junderw** 2021-08-21 23:54 UTC
