### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'makeRandom')

### ISSUE THREAD

**Issue by ruben2k1** [bitcoinjs/bitcoinjs-lib#1912] opened 2023-05-07 23:11 UTC
The method makeRandom() doesn`t exist

```
const bitcoin = require('bitcoinjs-lib');

// Generates a random private key
const keyPair = bitcoin.ECPair.makeRandom();

// Converts the private key to WIF
const privateKeyWIF = keyPair.toWIF();

// Generates the corresponding public address
const { address } = bitcoin.payments.p2pkh({ pubkey: keyPair.publicKey });

// Prints the private key and public address
console.log('Private key: ', privateKeyWIF);
console.log('Public address: ', address);
```

TypeError: Cannot read properties of undefined (reading 'makeRandom')
    at Object.<anonymous> (C:\xampp\htdocs\Pruebas\bitcoin\app.js:4:32)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

**Comment by junderw** [comment] 2023-05-08 02:19
Duplicate of #1911

**Closed by junderw** 2023-05-08 02:19 UTC

**Comment by ruben2k1** [comment] 2023-05-08 11:21
Could you make a more complete documentation?

**Comment by motorina0** [comment] 2023-05-08 11:25
There are many examples here
 - https://github.com/bitcoinjs/bitcoinjs-lib#examples

For the `bitcoin.payments.p2*`  you can check:
 - https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/payments.spec.ts

**Comment by ruben2k1** [comment] 2023-05-08 15:41
Okay, but `import { regtestUtils } from './_regtest';` doesn't work and it's in the example

I also installed regtest-client package and doesn't find regtestUtils too

**Comment by junderw** [comment] 2023-05-08 15:55
Is this your first time using TypeScript or JavaScript(ESModule import syntax)?

Did you try looking at the `_regtest.ts` file?

Also, these examples are using regtest-client which is only for testing on regtest. If you want to connect to your own node that requires using other libraries outside the scope of this library.

If you don't know what regtest is, or if you don't understand that regtestUtils is an abstraction layer for testing on a locally run bitcoin network, then you need to learn more about Bitcoin. https://developer.bitcoin.org/examples/testing.html

If you don't know that importing from `./_regtest` means to look at the file named `_regtest.{ts,js}` then learn about TypeScript here https://www.typescriptlang.org/docs/

Without a firm grasp of these two larger topics, it will be difficult to understand what's going on. If we did have documentation, the first part would say "learn TypeScript and how Bitcoin works before trying to use this library."

Our examples are not easily copy-pastable. You have to read them and understand them first, then you can write them on your own / copy small parts of it.

**Comment by ruben2k1** [comment] 2023-05-08 17:10
Ok, so when I understand how the library works I will use it. In the meantime I will use Bitcore, which explains the documentation better

Thank you for support

**Comment by junderw** [comment] 2023-05-08 18:10
> I will use Bitcore, which explains the documentation better

Good luck :+1: 

https://github.com/bitpay/bitcore/blob/v10.0.5/packages/bitcore-lib/README.md

https://github.com/bitpay/bitcore/issues
