### ISSUE TITLE
addInput parameters sequence and prevOutScript

### ISSUE THREAD

**Issue by caxco93** [bitcoinjs/bitcoinjs-lib#472] opened 2015-09-16 00:08 UTC
Hello, what is the sequence for in the addInput method?

TransactionBuilder.prototype.addInput = function (txHash, vout, sequence, prevOutScript)

im trying to add more than 1 input tx that come from the same address, 

```javascript
for (var a = 1; a < input_utxos.length; a++) {
    tx.addInput(input_utxos[a].tx, a);
}
```
like this. The tx hash works if my input_utxos has only 1 utxo. but it wont if it consists of 2 or more utxos, so i assume its because im not specifying a prevOutScript? 

**so... TL,DR**

what are `sequence` and `prevOutScript` from the addInput method for?

**EDIT:** 

```javascript
tx.addOutput(to, parseInt(amount));
var change_amount = sum_outputs - parseInt(amount);
if(change_amount > 0) {
    tx.addOutput(from, change_amount);
}
for(var a = 0; a < input_utxos.length; a++) {
    tx.sign(a, key);
}
//this is how im signing. currently no fee and change back to same address
```

**Comment by dcousens** [comment] 2015-09-16 05:46
@caxco93 for `sequence`,  see [this post on stackoverflow](https://bitcoin.stackexchange.com/questions/2025/what-is-txins-sequence).

As for `prevOutScript`,  it is used to provide `TransactionBuilder` with the previous outputs script,  thus allowing it to deduce more information about the transaction you are currently creating.
It is rarely needed,  usually only in cases of raw multisig or pay-to-pubkey (not pubkeyhash).

In your case, can you explain what you mean by:

> it wont work with more than 1

**Comment by caxco93** [comment] 2015-09-16 13:46
input_utxos is an array of utxos with the selected utxos that will make up for the amount needed. if my array has 1 utxo, it will generate a valid tx Hash that can be pushed to the network, but if my array has more than 1 utxo, it will generate a tx Hash that cant be pushed (in this case through blockchain push).

my decoded tx has looks like this right now:

```javascript
{
   "lock_time":0,
   "size":339,
   "inputs":[
      {
         "prev_out":{
            "index":0,
            "hash":"3a896625fce1f18ce4c3139863359631d5677cff4e4fd8dac25ca6327c0dadd8"
         },
         "script":"473044022070f3b03cca6a75038ffe150be347a97d0e07adc857cc93e245739db55e3a6d36022051eb72b21e35a5e7309e1864f00e1b107a5b5262d80b1128e9fb45fbe7971c7b012102bb05325000709d3a3d8063f9913777859b8fa30b83e4c4f981bb2d9781b7c91a"
      },
      {
         "prev_out":{
            "index":1,
            "hash":"436094120d4412c32b97738f9051a32a237c037abe31cafbdc8a02d16f2a659c"
         },
         "script":"483045022100da7abc59e24d2afea9219ee24d1f3df4e1b9a2efa154d9704ed903210abfdb40022015a8237d38e18f558172872af1aa5c244b38c3ad8f594463c0dcad18dbfcf5f5012102bb05325000709d3a3d8063f9913777859b8fa30b83e4c4f981bb2d9781b7c91a"
      }
   ],
   "version":1,
   "vin_sz":2,
   "hash":"c5991f9f044f9d829fc01eeda76f36a514271270f9f891ea7b584f504ed404ea",
   "vout_sz":1,
   "out":[
      {
         "script_string":"OP_DUP OP_HASH160 7ff85ee854794422531b7b5c3d380c5f50011a4e OP_EQUALVERIFY OP_CHECKSIG",
         "address":"1CfeMTtDP9HNjc8vsuuHGgUfABexvW5Qkf",
         "value":350000,
         "script":"76a9147ff85ee854794422531b7b5c3d380c5f50011a4e88ac"
      }
   ]
}
```

and i get a OP_EQUALVERIFY: non-equal data message. Which after some research I found out that it means the address from the uncompressed public key extracted from the scriptSig does not match the address im sending xbt to. So this made me think they were being wrongly calculated because im not using all the necessary parameters when adding.

**PS:** I edited my original post to show how im signing

**Comment by dcousens** [comment] 2015-09-26 04:47
@caxco93 what version of `bitcoinjs-lib` are you using?
Is `tx` a `TransactionBuilder`?

**Comment by dcousens** [comment] 2015-09-26 04:48
Ah wait,  @caxco93 I see it.
You're not adding the inputs correctly.

``` javascript
for (var a = 1; a < input_utxos.length; a++) {
    tx.addInput(input_utxos[a].tx, a);
}
```

Should be

``` javascript
for (var a = 1; a < input_utxos.length; a++) {
    tx.addInput(input_utxos[a].tx, input_utxos[a].vout);
}
```

**Comment by dcousens** [comment] 2015-09-26 04:49
Duplicate of https://github.com/bitcoinjs/bitcoinjs-lib/issues/339

**Comment by dcousens** [comment] 2015-09-26 04:50
Closing,  please re-open if this is not the problem.

**Closed by dcousens** 2015-09-26 04:50 UTC
Labels: question

**Comment by coincrypto** [comment] 2017-11-24 10:40
@dcousens Thank for this useful lib, I'm doing this to sign litecoin transaction. 
Here is my code
`
var bitcoin = require('bitcoinjs-lib');
var litecoin_network = bitcoin.networks.litecoin
var tx = new bitcoin.TransactionBuilder(litecoin_network)
//bellow is my 3 unspents tx with correct vout, all this tx is belong to this address LLD5Mz3ftVkTJwEJr9AU4DVUY1t8SwZRwN
//for my transaction, I need to spent these 3 unspentxs
privateKey = 'xxxxxx' //this is private of address LLD5Mz3ftVkTJwEJr9AU4DVUY1t8SwZRwN
tx.addInput('a83bee9e505367a3e420037057066ec1c1c07cbc80ed864ab3160c7ad1d337c0', 0 )
tx.addInput('bf3c35496be71ee7bc3fed6af5b8df5a333623cb3079aaa18630003b6c17ce4f', 0)
tx.addInput('d0661788b82ade9295fb6c4dfe48b662e3a7e22cc4af6d04e12f012f7c330111', 1)

tx.addOutput('LLD5Mz3ftVkTJwEJr9AU4DVUY1t8SwZRwN', 750000)//this address I send back my LTC
tx.addOutput('LUsyDGs8C5tykwMdby16bK3dGqkmx61t3D', 17695500)// this address I will send to
var keyPair = bitcoin.ECPair.fromWIF(privateKey, litecoin_network)
tx.sign(0, keyPair)
console.log(tx.build().toHex())
`
When I execute this code, error as bellow
`node_modules/bitcoinjs-lib/src/transaction_builder.js:633
    if (!scriptType && !allowIncomplete) throw new Error('Transaction is not complete')
                                         ^
`
This code will run well if I just only run only one `tx.addInput` function.
Could you help to take a look?
