### ISSUE TITLE
react-native bitcoinjs install issues

### ISSUE THREAD

**Issue by wmpedersen** [bitcoinjs/bitcoinjs-lib#976] opened 2018-01-02 19:56 UTC
I'm trying to implement bitcoinjs-lib in react-native, but I get errors when it looks for Buffer and other crypto libraries. I have used rn-nodeify as referenced in #582 and #797 and imported the shim but it's still complaining. My install process to include bitcoinjs-lib/bip39 is as follows:

`npm install --save bitcoinjs-lib bip39 react-native-crypto`
`npm install` (at this point the post-install does `rn-nodeify --install fs,dgram,process,path,console --hack`)
`react-native start` and `react-native run-android` for my emulator

react-native is still complaining about stream, and once I include stream it complains about buffer/safe-buffer/cipher-base and once I include any of those and rebuild it gives the infamous "Can't find variable Buffer" 

I've read around that others have got it to work but have yet to be able to build it myself. Any pointers in the install process?

**Comment by dcousens** [comment] 2018-01-17 01:09
@wmpedersen could you please post your log dump from `npm install`?

**Comment by wmpedersen** [comment] 2018-01-17 04:18
@dcousens it doesn't seem like an issue with my app including bitcoinjs - there's no problem with npm install (other than the dependencies), more of how I include it in a react-native app. I've got the dependencies listed below in my app's node_modules folder, so I don't know why it's not finding them...

```npm WARN @storybook/addon-storyshots@3.3.3 requires a peer of babel-core@^6.26.0 | ^7.0.0-0 but none is installed. You must install peer dependencies yourself. 

npm WARN @storybook/react-native@3.3.3 requires a peer of babel-core@^6.26.0 | ^7.0.0-0 but none is installed. You must install peer dependencies yourself. 

npm WARN react-native-crypto@2.1.2 requires a peer of react-native-randombytes@>=2.0.0 <4.0.0 but none is installed. You must install peer dependencies yourself. 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 9.247s```

**Comment by wmpedersen** [comment] 2018-01-18 02:51
weird, now it's giving me secure RNG issues...

**Comment by dcousens** [comment] 2018-01-18 03:16
@wmpedersen it may seem like no one is listening,  but I guarantee any information you post about the problems your having will help *someone* in the future,  so please post the details :+1:

**Comment by wmpedersen** [comment] 2018-01-18 03:46
seems like it's doing [the same thing](https://github.com/bitcoinjs/bitcoinjs-lib/issues/559#issuecomment-203698049) but I have [react-native-randombytes^3.0.0](https://github.com/bitcoinjs/bitcoinjs-lib/issues/559#issuecomment-205040571)

I don't know what changed. I might just try from my test repo from the beginning again and add my code. I was messing about with things - I seem to remember `import com.bitgo.randombytes.RandomBytesPackage` in my android app - but for some reason it's gone now. It's good to know it was working and I should be able to replicate it. I'll have to write down the steps as I go along.

**Comment by wmpedersen** [comment] 2018-01-18 05:03
So no matter what I've done I can't seem to put it back in my working state. My project uses react-native-randombytes properly in terms of importing it into the project again, but it seems bip39 is still complaining about my RNG because it's still trying to use non-react randombytes.

**Comment by dcousens** [comment] 2018-02-25 00:02
@corey-phillips you understand you could pass in `myRng` as the `options` argument, `{ rng: myRng }` instead of modifying the library,  no?

Additionally,  your RNG is initializing the `mt19937` every time... what does `autoSeed` do?  This **does not** look cryptocraphically safe and I'd advise others against using this.

**Comment by coreyphillips** [comment] 2018-02-25 00:18
Thanks @dcousens. I've updated the makeRandom function to reflect your input. 

Regarding the myRng function, is there anything that you would suggest implementing there that would be both cryptographically secure and compatible for a React Native implementation?

**Comment by dcousens** [comment] 2018-02-25 00:19
``` js 
    var num = random.int32();
    buf.fill(num)
    return buf
```

int32 is not 32-bytes, its 32-bits. That is a Buffer of 32 copies of the same number...

**Comment by dcousens** [comment] 2018-02-25 00:28
@coreyphillips was the following https://github.com/bitcoinjs/bitcoinjs-lib/issues/559#issuecomment-205040571 not helpful to you?

**Comment by coreyphillips** [comment] 2018-02-25 00:50
@dcousens I did see that. Unfortunately, react-native-randombytes continues to throw an error. Still more troubleshooting ahead. Almost there though :-)

**Comment by coreyphillips** [comment] 2018-02-25 01:08
Huzzah, looks like it may have been a linking issue with react-native-randombytes. It appears to be working now.

I've updated the ecpair.js file [here](https://github.com/coreyphillips/react-native-bitcoinjs-lib/blob/master/src/ecpair.js). The only change made to the file is the require for `react-native-randombytes` instead of `randombytes`.

**Comment by dabura667** [comment] 2018-02-25 01:22
> The only change made to the file is the require for react-native-randombytes instead of randombytes.

Again, you don't need to modify bitcoinjs for this. You can pass react-native-randombytes as an argument to ECPair.

**Comment by coreyphillips** [comment] 2018-02-25 02:05
Thanks @dabura667. Understood.

**Comment by dcousens** [comment] 2018-03-21 04:13
> This appears to be the only remaining issue encountered when using this library in RN.

What about the other `reverse()` calls?

`tx.getId`?

**Comment by coreyphillips** [comment] 2018-03-23 02:38
@dcousens, you are correct. The remaining `.reverse()` calls fail as well and would require a similar update as the example above in order to get it working in a RN project.

**Comment by dcousens** [comment] 2018-03-23 05:02
@corey-phillips OK... I'm not against re-introducing `buffer-reverse` for the sake of RN... but,  it is a bit frustrating.
Why isn't RN addressing this with an up-to-date `Buffer`?

**Comment by coreyphillips** [comment] 2018-03-24 01:08
@dcousens Basically what dabura667 said.

**Comment by jackylimel** [comment] 2018-04-30 06:08
@corey-phillips the solution mentioned here works fine on simulator or debugging on device: https://github.com/bitcoinjs/bitcoinjs-lib/issues/976#issuecomment-368261162, however, when I package an release APK file and install it on device, then I get error:

ReactNativeJS: TypeError: undefined is not a function (evaluating 'Error.captureStackTrace(this,y)')

**Comment by dcousens** [comment] 2018-04-30 06:16
@jackylimel great to know!
I wasn't aware that `Error.captureStackTrace` wasn't standard to JS,  but V8-specific.
It is used by https://github.com/dcousens/typeforce ... that will need to be fixed.

**Comment by jackylimel** [comment] 2018-05-01 00:25
The weird thing is. If I just call `bjs.ECPair.makeRandom()`, then it works fine on both `debug` and `release` mode, but if I call `bjs.HDNode.fromBase58('example_xpub_key')`, then it would succeed on `debug` mode but fails on `release` mode ( running as a signed apk file, even on simulator).

Could someone please help?

**Comment by jackylimel** [comment] 2018-05-01 01:34
I've found the problem is caused by `uglifijs` and will use the solution here: 

https://github.com/facebook/react-native/issues/9711#issuecomment-327552716

**Comment by dcousens** [comment] 2018-05-01 01:55
@jackylimel so,  `Error.captureStackTrace` is no longer `undefined`?

**Comment by jackylimel** [comment] 2018-05-01 01:58
Once I apply the patches for uglifyjs, then I no longer get typeforce error...

**Comment by DaniGuardiola** [comment] 2018-05-24 12:41
hello :)
what is the status of this? is this documented somewhere?

**Comment by zhaozhiming** [comment] 2018-06-15 06:03
Same problem here. [The solution mentioned here](https://github.com/bitcoinjs/bitcoinjs-lib/issues/976#issuecomment-368261162) not work for me. It make the project can't start.  
Any other solution or document of this problem?

**Comment by dcousens** [comment] 2018-06-15 06:12
> not work for me. 

If you can outline _what_ doesn't work for you,  maybe we can help.

**Comment by zhaozhiming** [comment] 2018-06-15 06:46
The error as follow:  
```
The package at "node_modules/sjcl/sjcl.js" attempted to import the Node standard library module "crypto". It failed because React Native does not include the Node standard library.
```
I think it's the `sjcl` useing the node library `crypto`, and the `sjcl` was depended by `react-native-randombytes`  

```
➜  react-native-bitcoinjs git:(master) ✗ yarn why sjcl
yarn why v1.5.1
[1/4] 🤔  Why do we have the module "sjcl"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "sjcl@1.0.7"
info Reasons this module exists
   - "react-native-randombytes" depends on it
   - Hoisted from "react-native-randombytes#sjcl"
info Disk size without dependencies: "540MB"
info Disk size with unique dependencies: "540MB"
info Disk size with transitive dependencies: "540MB"
info Number of shared dependencies: 0
✨  Done in 1.87s.
```

My Env:
```
  Node: 6.9.2
  Yarn: 1.5.1
  npm: 3.10.9
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  expo: ^27.0.1 => 27.1.0
  react: 16.3.1 => 16.3.1
  react-native: ~0.55.2 => 0.55.4
```

This is the issue: https://github.com/mvayngrib/react-native-randombytes/issues/10

**Comment by dcousens** [comment] 2018-06-15 06:49
@zhaozhiming maybe you should bump https://github.com/mvayngrib/react-native-randombytes/issues/10 for answers?

As for how we could resolve this... we could optionally remove the default `rng` entirely from our dependency tree, meaning users would have to specify the `rng` in `ECPair.makeRandom`.

But that seems a bit overkill.
It maybe a solution for `react-native` users though...

**Comment by zhaozhiming** [comment] 2018-06-15 07:35
OK, Thank you.   
BTW a question, the best practices of `bitcoinjs-lib` is to run in **Node.js** environment but not **Browser** like environment, right?

**Comment by zhaozhiming** [comment] 2018-06-16 11:13
Could `bitcoinjs-lib` implement  the `ramdomBytes` like [this](https://github.com/ethers-io/ethers.js/blob/aa48dfcdf4e1030b046bffc57dd3ed7607c7123c/utils/browser-random-bytes.js)?

That library can use different `randomBytes` according with the environment, whether it’s  Node.js or Browser.

**Comment by junderw** [comment] 2018-06-18 08:00
> Could bitcoinjs-lib implement the ramdomBytes like this?

That is reeeeally insecure.................. console.log with a warning is not sufficient. The randomness of those values should not be anywhere near an app that generates private keys.

**Comment by junderw** [comment] 2018-06-18 08:01
looping 20 rounds shows that the person who made this has no understanding of how Math.random works.

**Comment by ShayanJa** [comment] 2018-08-05 01:37
Do you have `react-native-crypto` & `react-native-randombytes` installed and linked? 
You will need to change all import occurences of randombytes, and crypto, with their react-native equivalent

**Comment by rikardwissing** [comment] 2018-08-12 19:14
I solved the missing buffer.reverse() simply by adding the following code to my shim.js.

`if (typeof Buffer.prototype.reverse === 'undefined') {
	var bufferReverse = require('buffer-reverse');

	Buffer.prototype.reverse = function () {
		return bufferReverse(this);
	};
}`

**Comment by coreyphillips** [comment] 2018-08-19 14:36
@ShayanJa, to prevent updating or changing the sjcl/sjcl.js file, you can instead:

1. Add "crypto" to your postinstall.
2. Uncomment `require('crypto')` at the bottom of shim.js. Or add `require('crypto')` to the bottom of shim.js if it doesn't exist.

**Comment by coreyphillips** [comment] 2018-08-20 13:37
Using the feedback from this thread I've created a gist that documents the setup process for getting version 4.0.1 of bitcoinjs-lib up and running in RN. Hopefully it will help to close this issue. Please let me know if there are any glaring issues or if you have any feedback in general.

- https://gist.github.com/coreyphillips/f33d86f3d2307e58f0a5686e6cfc8a7e

**Comment by cbrwizard** [comment] 2018-09-28 09:31
@coreyphillips followed the gist, receiving this error on start:
```
error: bundling failed: Error: While trying to resolve module `./payments` from file `/Users/cbrwizard/apps/mothership/exchange/MothershipCompanion/node_modules/bitcoinjs-lib/src/index.js`, the package `/Users/cbrwizard/apps/mothership/exchange/MothershipCompanion/node_modules/bitcoinjs-lib/src/payments/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/cbrwizard/apps/mothership/exchange/MothershipCompanion/node_modules/bitcoinjs-lib/src/payments/_testnet.js`. Indeed, none of these files exist:
```

**Comment by coreyphillips** [comment] 2018-09-28 14:15
@cbrwizard Regarding your initial error, you'll want to make sure to apply the following step:

> **Resolve Item In bitcoinjs-lib/src/payments/package.json**
> Open package.json in .../bitcoinjs-lib/src/payments/package.json and replace "main": "_testnet.js", with the following: "main": "index.js",

Regarding update 2 & 3, you should only need to add vm to your postinstall, but, hey, if it works... :smile:

**Comment by junderw** [comment] 2018-10-01 01:55
4.0.2 gets rid of the package.json btw

**Comment by cbrwizard** [comment] 2018-10-01 05:37
Is there a way to automate these changes inside the node_modules btw? Because hard-coding them looks wrong and the changes get reverted back on packages installation

**Comment by dcousens** [comment] 2018-10-01 05:46
@cbrwizard what changes are you referring to specifically?

**Comment by cbrwizard** [comment] 2018-10-01 06:08
Had to switch to bitcoinjs-lib because the react native one is very outdated. Luckily, it worked after I followed https://gist.github.com/coreyphillips/f33d86f3d2307e58f0a5686e6cfc8a7e, so thanks @coreyphillips !

@dcousens I had to manually apply this change in my project's node module:

Open package.json in .../bitcoinjs-lib/src/payments/package.json and replace "main": "_testnet.js", with the following: "main": "index.js",

**Comment by coreyphillips** [comment] 2018-10-01 13:18
Thanks @cbrwizard. I've updated the 4.0.2 gist: https://gist.github.com/coreyphillips/928ae27ccea69cd0b494d13ad2b3f27d

I'm going to do my best to update and maintain a RN compatible repo here (https://github.com/coreyphillips/rn-bitcoinjs-lib) with setup instructions if you ever need it for reference.

**Comment by harunsmrkovic** [comment] 2018-11-08 16:42
If you are experiencing issues with this library working fine in Simulator/Debug mode, but not working when preparing for release, you need to disable `mangle` from `uglify`.

No need to patch anything though, just add the following to your `metro.config.js` file:

```
module.exports = {
  transformer: {
    minifierConfig: {
      mangle: {
        keep_fnames: true
      }
    }
  }
}
```

🎉

**Comment by junderw** [comment] 2019-07-25 08:06
Can anyone here check if the most recent version still has any of these issues.

We have switched to TypeScript, so some issues might just be solvable by messing with tsconfig.json???

**Comment by coreyphillips** [comment] 2019-07-25 13:32
Versions tested:
```
"bitcoinjs-lib": "5.1.1",
"react-native": "0.60.4"
```
@junderw, the more recent versions definitely seem to have smoothed out a few of the previous issues. Using the versions listed above the minimum amount of work required to get it running in RN (as far as I can tell) is as follows: https://gist.github.com/coreyphillips/4d45160fed016417a5f583f179c2cbdb

**Comment by junderw** [comment] 2019-07-25 13:38
@coreyphillips hmmm... I thought I removed all Buffer.prototype.reverse() instances...

Is that really needed?

**Comment by coreyphillips** [comment] 2019-07-25 13:54
@junderw Awesome, you're correct, it isn't needed. I just forgot to remove the condition in `shim.js` that was causing a `buffer-reverse` error to throw. The Gist has been updated accordingly.

**Closed** 2024-05-01 10:29 UTC
Labels: external, how to / question / docs
