### ISSUE TITLE
isPubKeyHashOutput not working as expected

### ISSUE THREAD

**Issue by frndxyz** [bitcoinjs/bitcoinjs-lib#586] opened 2016-06-08 06:49 UTC
Here is a raw transaction. its failed to validate vout 1.

``` json
{
   "txid": "32faeb5f70b032bafcf547fdce735b7add7d00ef5d5c716c8832c42a2b063d9d",
   "version": 1,
   "locktime": 0,
   "vin": [
      {
         "coinbase": "03d07c032cfabe6d6df8f4f61cac03806ff19845dce34b753beb8f0f45028b7242eec15669ed0883420100000000000000062f503253482f",
         "sequence": 4294967295
      }
   ],
   "vout": [
      {
         "value": 3e-8,
         "n": 1,
         "scriptPubKey": {
            "asm": "04ffd03de44a6e11b9917f3a29f9443283d9871c9d743ef30d5eddcd37094b64d1b3d8090496b53256786bf5c82932ec23c3b74d9f05a6f95a8b5529352656664b OP_CHECKSIG",
            "hex": "4104ffd03de44a6e11b9917f3a29f9443283d9871c9d743ef30d5eddcd37094b64d1b3d8090496b53256786bf5c82932ec23c3b74d9f05a6f95a8b5529352656664bac",
            "reqSigs": 1,
            "type": "pubkey",
            "addresses": [
               "Aakx45L1Z2z1Y3eq4jYaufNc3J439Xyegb"
            ]
         }
      }
   ]
}
```

**Comment by dcousens** [comment] 2016-06-08 06:55
Reproduced.

``` javascript
var assert = require('assert')
var script = require('./').script

assert(
  script.isPubKeyHashOutput(
    new Buffer('03d07c032cfabe6d6df8f4f61cac03806ff19845dce34b753beb8f0f45028b7242eec15669ed0883420100000000000000062f503253482f', 'hex')
  )
)
```

**Comment by frndxyz** [comment] 2016-06-08 06:59
@dcousens i am taking about output , not input . i mean how to handle  pay-to-pubkey.

**Comment by dcousens** [comment] 2016-06-08 07:00
@frndxyz right.

``` js
var assert = require('assert')
var script = require('./').script

var s = new Buffer('4104ffd03de44a6e11b9917f3a29f9443283d9871c9d743ef30d5eddcd37094b64d1b3d8090496b53256786bf5c82932ec23c3b74d9f05a6f95a8b5529352656664bac', 'hex')
console.log(script.toASM(s))

assert(script.isPubKeyOutput(s))
```

Works for me.
Whats the issue?

**Comment by dcousens** [comment] 2016-06-08 07:01
Perhaps you meant `isPubKeyOutput` not `isPubKeyHashOutput`?

**Comment by dcousens** [comment] 2016-06-08 07:04
Whatever gave you the OP JSON is misleading with the `.addresses` field,  a `pubkey` output does **not** have an implicit address for its script,  but you can derive a `pubkeyhash` script from the public key inside the `pubkey` script.

**Comment by frndxyz** [comment] 2016-06-08 07:06
var address = bitcoin.Address.fromOutputScript(out.script, network).toString()

above line is failed to get address from output.

**Comment by dcousens** [comment] 2016-06-08 07:09
@frndxyz as it should.

That script does *not* have an address.
That script is of the form: `{pubKey} OP_CHECKSIG`

The only scripts that have addresses are: pay-to-pubkeyhash and pay-to-scripthash.
pay-to-pubkey does not have an address.

However,  you can take the `pubKey` out of the pay-to-pubkey script,   and derive an address for it:  `OP_DUP OP_HASH160 {hash160(pubKey)} OP_EQUALVERIFY OP_CHECKSIG`

**Comment by frndxyz** [comment] 2016-06-08 07:11
this lead to payment failed at hive-wallet. any idea how can i derive "pubKey" from pay-to-pubkey?

**Comment by dcousens** [comment] 2016-06-08 07:15
@frndxyz this should be what you want:


``` javascript
let { address, crypto, script} = require('bitcoinjs-lib')

assert(script.isPubKeyOutput(out.script))

address.fromOutputScript(
  script.pubKeyHashOutput(
    crypto.hash160(
      script.decompile(out.script)[0] // the public key chunk
    )
  )
)
```

Or,  due to the nature of P2PKH addresses being literally just the hash:
``` javascript
// ...

address.toBase58Check(
  crypto.hash160(
    script.decompile(out.script)[0] // the public key chunk
  )
)
```

**Comment by frndxyz** [comment] 2016-06-08 07:17
its failed here , if you later can fix in bitcoin-js lib.


function getCandidateOutputs(allNodes, metadata, network, myAddresses, minConf) {
  var confirmedNodes = allNodes.filter(function(n) {
    var meta = metadata[n.id]
    return meta && meta.confirmations >= minConf
  })

  return confirmedNodes.reduce(function(unspentOutputs, node) {
    node.tx.outs.forEach(function(out, i) {
      var address = bitcoin.Address.fromOutputScript(out.script, network).toString()
      if(myAddresses.indexOf(address) >= 0 && node.nextNodes[i] == null) {
        unspentOutputs.push({
          txId: node.id,
          address: address,
          value: out.value,
          vout: i
        })
      }
    })

    return unspentOutputs
  }, [])
}

**Comment by dcousens** [comment] 2016-06-08 07:18
@frndxyz there isn't a bug here,  I'm not sure what you want me to fix.

**Comment by dcousens** [comment] 2016-06-08 07:20
The code above assumes that there is always an address for `out.script`,  which is blatantly incorrect.
If you're confused,  imagine that `out.script` was an `OP_RETURN`.

**Comment by frndxyz** [comment] 2016-06-08 07:20
ok, see raw transaction here https://chainz.cryptoid.info/aur/tx.dws?32faeb5f70b032bafcf547fdce735b7add7d00ef5d5c716c8832c42a2b063d9d.htm

**Comment by dcousens** [comment] 2016-06-08 07:21
@frndxyz what am I meant to be seeing there?

**Comment by frndxyz** [comment] 2016-06-08 07:23
at outs: {n:5}  when getting address by 
"var address = bitcoin.Address.fromOutputScript(out.script, network).toString()"   this assert failed  assert(false, script.toASM() + ' has no matching Address')

**Comment by dcousens** [comment] 2016-06-08 07:25
``` json
      {
         "value": 3e-8,
         "n": 5,
         "scriptPubKey": {
            "asm": "04ffd03de44a6e11b9917f3a29f9443283d9871c9d743ef30d5eddcd37094b64d1b3d8090496b53256786bf5c82932ec23c3b74d9f05a6f95a8b5529352656664b OP_CHECKSIG",
            "hex": "4104ffd03de44a6e11b9917f3a29f9443283d9871c9d743ef30d5eddcd37094b64d1b3d8090496b53256786bf5c82932ec23c3b74d9f05a6f95a8b5529352656664bac",
            "reqSigs": 1,
            "type": "pubkey",
            "addresses": [
               "Aakx45L1Z2z1Y3eq4jYaufNc3J439Xyegb"
            ]
         }
      },
```

It isn't a pay-to-pubkeyhash output,  its pay-to-pubkey,  thereby,  it doesn't have an address.
Working as expected?

**Comment by frndxyz** [comment] 2016-06-08 07:26
it calls this assert(false, script.toASM() + ' has no matching Address') and payment failed.

**Comment by frndxyz** [comment] 2016-06-08 07:31
if (scripts.isPubKeyHashOutput(script)) return new Address(script.chunks[2], network.pubKeyHash)
if (scripts.isScriptHashOutput(script)) return new Address(script.chunks[1], network.scriptHash)

this both condition failed with that pay-to-pubkey output.

i know i am confusing you by my bad language, but this is one of the rare case, all other wallet transaction works.

**Comment by dcousens** [comment] 2016-06-08 07:34
> this both condition failed with that pay-to-pubkey output.

Because it should,  `pay-to-pubkey`scripts **have no matching address**.

**Comment by dcousens** [comment] 2016-06-08 07:36
To help you out,  here is your function fixed:

``` javascript
function getCandidateOutputs(allNodes, metadata, network, myAddresses, minConf) {
  var confirmedNodes = allNodes.filter(function(n) {
    var meta = metadata[n.id]
    return meta && meta.confirmations >= minConf
  })

  return confirmedNodes.reduce(function(unspentOutputs, node) {
    node.tx.outs.forEach(function(out, i) {
      if (!bitcoin.isPubKeyHashOutput(out.script)) continue // skip non pay-to-pubkeyhash outputs

      var address = bitcoin.Address.fromOutputScript(out.script, network).toString()
      if(myAddresses.indexOf(address) >= 0 && node.nextNodes[i] == null) {
        unspentOutputs.push({
          txId: node.id,
          address: address,
          value: out.value,
          vout: i
        })
      }
    })

    return unspentOutputs
  }, [])
}
```

**Comment by frndxyz** [comment] 2016-06-08 07:36
so how to ignore and let transaction work. 
should i remove this line   "assert(false, script.toASM() + ' has no matching Address)"

**Comment by dcousens** [comment] 2016-06-08 07:37
@frndxyz it will not work without larger modifications to your overall code.   You need to know how to distinguish between addresses and raw scripts.

**Comment by frndxyz** [comment] 2016-06-08 07:40
ok , thank you very much for quick reply and function fixes @dcousens .

**Comment by dcousens** [comment] 2016-06-08 07:41
@frndxyz no worries,  just note that you will not be able to *spend* vout 5 unless you add in that extra functionality,  which is non trivial.

You will need to store the relevant scripts and pass them to the `TransactionBuilder` when you go to spend them.

**Comment by frndxyz** [comment] 2016-06-08 07:44
yeah ,got it...

**Comment by dcousens** [comment] 2016-06-08 07:53
@frndxyz closing it shouldn't hide it from search results,  and therefore it should remain useful to others.

**Closed by dcousens** 2016-06-08 07:53 UTC
Labels: question
