### ISSUE TITLE
Ability to validate an address

### ISSUE THREAD

**Issue by jackmallers** [bitcoinjs/bitcoinjs-lib#890] opened 2017-09-14 02:42 UTC
Would be nice to have the ability to easily check if a Bitcoin address is valid :)

**Comment by dcousens** [comment] 2017-09-14 02:46
(edited title to reflect email context)

**Comment by jackmallers** [comment] 2017-09-14 03:58
Should the functionality include any address at all as well @dcousens? Just don't want to pull in separate tools to validate segwit vs regular

**Comment by dcousens** [comment] 2017-09-14 04:53
@jackmallers best practice is to:

``` js
function validate (address) {
  try {
    bitcoin.address.toOutputScript(address)
    return true
  } catch (e) {
    return false
  }
}
```

And if we added it as an API function or example,  it would undoubtedly be the same.

**Comment by jackmallers** [comment] 2017-09-14 15:30
@dcousens agree, that looks great 👍

**Comment by dcousens** [comment] 2017-09-15 01:26
@jackmallers that works ^,  if that resolves your question

**Comment by jackmallers** [comment] 2017-09-15 19:22
@dcousens so I created 3 addresses to test on testnet:
`p2pkh`: `mpR4D7zjxUD2EM5FzDLGasmLLUETkzPx3E`
`p2wkh`: `tb1qhdgnhnjdagv0fv4z00yy6pqqfcdrfp3dvl7waa`
`np2wkh`: `2NFjYV3YZ2PYyNE3ewgoMisKnKyE7vRtCdB`

`p2pkh` and `np2wkh` validates, but `p2wkh` does not. I will look at the source good in a bit to try and debug

**Comment by dcousens** [comment] 2017-09-16 01:28
How did you create them?
And what is NP2WKH?

**Comment by dabura667** [comment] 2017-09-16 01:34
@jackmallers worked for me...

```javascript
> bitcoin.address.toOutputScript('tb1qhdgnhnjdagv0fv4z00yy6pqqfcdrfp3dvl7waa',bitcoin.networks.testnet)
//<Buffer 00 14 bb 51 3b ce 4d ea 18 f4 b2 a2 7b c8 4d 04 00 4e 1a 34 86 2d>
```

**Comment by dabura667** [comment] 2017-09-16 01:35
@dcousens P2SH-P2WPKH is what he's referring to.

Nested Pay 2 Witness Key Hash

**Comment by jackmallers** [comment] 2017-09-16 16:51
@dcousens does `bitcoin.address.toOutputScript('tb1qhdgnhnjdagv0fv4z00yy6pqqfcdrfp3dvl7waa', bitcoin.networks.testnet)` work for you as well?

I must be doing something really dumb that I'm missing, I'm getting `Error: Non-base58 character`

**Comment by dabura667** [comment] 2017-09-16 16:56
@jackmallers did you install via npm?

latest npm version doesn't support bech32 yet.

`npm install https://github.com/bitcoinjs/bitcoinjs-lib.git` should work better.

**Comment by dcousens** [comment] 2017-09-17 00:06
3.2.0 released in https://github.com/bitcoinjs/bitcoinjs-lib/pull/892,  @jackmallers if you run `npm install bitcoinjs-lib@latest`,  your issue should resolve.

**Closed by dcousens** 2017-09-17 00:06 UTC
Labels: how to / question / docs

**Comment by jackmallers** [comment] 2017-09-21 03:52
sorry forgot to report back, works great @dcousens 

thanks

**Comment by Aaaaaashu** [comment] 2017-10-25 12:35
When I use `bitcoin.address.toOutputScript` to check a correct address，it's not work.

```javascript
try {
    bitcoin.address.toOutputScript(‘1MPd34theheiGStaxaVBaLDFi75e8kkwvm’)
  } catch (e) {
    console.log(e.message) // ' has no matching Script'
    return false
  }
```

I found that this error occurred in this code when I tried debug

```javascript
function decodeRaw (buffer) {
  var payload = buffer.slice(0, -4)
  var checksum = buffer.slice(-4)
  var newChecksum = sha256x2(payload)

  if (checksum[0] ^ newChecksum[0] |
      checksum[1] ^ newChecksum[1] |
      checksum[2] ^ newChecksum[2] |
      checksum[3] ^ newChecksum[3]) return

  return payload
}
```

**Context:**
React Native 0.47
macOS Sierra

**Comment by dcousens** [comment] 2017-10-25 14:31
@Aaaaaashu `react-native` is probably the issue,  but I can't say for sure without further context/debugging information.

**Comment by Aaaaaashu** [comment] 2017-10-26 02:51
@dcousens yep, when I use the Node environment, it's work.

**Comment by coreyphillips** [comment] 2017-12-04 14:41
@Aaaaaashu, I ran into this as well. The issue is `buffer.slice`. You will want to use a library similar to this in order to perform that action, "https://www.npmjs.com/package/arraybuffer.slice"

**Comment by Aaaaaashu** [comment] 2017-12-05 05:19
@coreyphillips 
Thank you
I solved this issue when I upgraded rn-nodeify and buffer.

**Comment by maximilliangeorge** [comment] 2019-01-22 21:34
At time of writing the official releases (the npm repository) do not support regtest address validation. It took me a while to realise I had to update from the github repository directly, using a newer commit hash. Just thought I'd mention it if someone else has the same issue.
