### ISSUE TITLE
[question] Transaction builder not building

### ISSUE THREAD

**Issue by runn1ng** [bitcoinjs/bitcoinjs-lib#644] opened 2016-10-05 19:30 UTC
I am trying to construct a transaction using TransactionBuilder and I am doing something wrong, but I can't tell what.

I have this transaction
https://testnet.blockexplorer.com/tx/0eb90544be26a25942ee61bbaea5e990d0290895cd0ba94127432a0c930b5775

I want to use the first output as an input.

I am doing this:

````javascript
const privkey = 'private key, belonging to address mowxUGLvamMSYyCUMMzChxgBosUQDvsAMk';
const privkeypair = bitcoin.ECPair.fromWIF(privkey, bitcoin.networks.testnet);
const txhex = 'transaction in hex';
const transaction = bitcoin.Transaction.fromHex(txhex);
const builder = new bitcoin.TransactionBuilder(bitcoin.networks.testnet);
builder.addInput(transaction, 0, 0);
builder.addOutput("n4pSwWQZm8Wter1wD6n8RDhEwgCqtQgpcY", 6000);
builder.sign(0, privkeypair);
````

And I get this error (using latest in npm)

````
Error: pubkeyhash not supported
    at TransactionBuilder.sign (.../node_modules/bitcoinjs-lib/src/transaction_builder.js:482:56)
    (my file here)
````

Or this error, using master

````
node_modules/bitcoinjs-lib/src/transaction_builder.js:482
  if (!valid) throw new Error('Key pair cannot sign for this input')
              ^

Error: Key pair cannot sign for this input
    at TransactionBuilder.sign (.../node_modules/bitcoinjs-lib/src/transaction_builder.js:482:21)
    (my file here)
````

What am I doing wrong?

**Comment by runn1ng** [comment] 2016-10-05 19:59
Well, let's try with this transaction instead, it's already spent, so I can show the private key.

https://testnet.blockexplorer.com/tx/393b227a1cb669b4277a693f0d8ee521e62ddce9ca4cdb97f0cc4fc735585932

`cV6Fs4jspcMmUoPXyQSAVkVDfNVjL2Sn8HsBwpDvmKdhF5A9CkQW` is the private key to `mjfVsKHRFQyFTFSqETGVLZf5NTjkEhVLhT`. The tx is already spent, but builder shouldn't notice. My code is:


````javascript
"use strict";

const bitcoin = require('bitcoin.js');

const privkey = 'cV6Fs4jspcMmUoPXyQSAVkVDfNVjL2Sn8HsBwpDvmKdhF5A9CkQW';
const txhex = '0100000001f7e6430096cd2790bac115aaab22c0a50fb0a1794305302e1a399e81d8d354f4020000006a47304402205793a862d193264afc32713e2e14541e1ff9ebb647dd7e7e6a0051d0faa87de302205216653741ecbbed573ea2fc053209dd6980616701c27be5b958a159fc97f45a012103e877e7deb32d19250dcfe534ea82c99ad739800295cd5429a7f69e2896c36fcdfeffffff0340420f00000000001976a9145c7b8d623fba952d2387703d051d8e931a6aa0a188ac8bda2702000000001976a9145a0ef60784137d03e7868d063b05424f2f43799f88ac40420f00000000001976a9145c7b8d623fba952d2387703d051d8e931a6aa0a188ac2fcc0e00';

const privkeypair = bitcoin.ECPair.fromWIF(privkey, bitcoin.networks.testnet);
const transaction = bitcoin.Transaction.fromHex(txhex);
const builder = new bitcoin.TransactionBuilder(bitcoin.networks.testnet);
builder.addInput(transaction, 0, 0);
builder.addOutput("n4pSwWQZm8Wter1wD6n8RDhEwgCqtQgpcY", 6000);
builder.sign(0, privkeypair); // <- error here
````

This should just work. But it doesn't :(

When I go into transaction_builder and change this line in PrepareInput - https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/transaction_builder.js#L209

````javascript
  // maybe we have some prior knowledge
  } else if (input.prevOutType) {
````

into
````javascript
  // maybe we have some prior knowledge
  } else if (input.prevOutType && false) {
````

it starts working, and the transaction seems to be signed correctly. So it seems to be a bug to me.

**Comment by jprichardson** [comment] 2016-10-05 20:03
The issue is that `addInput` requires the txHash. See this for an example: https://github.com/bitcoinjs/bitcoinjs-lib/blob/4ae06003c4b38aa2335a152e12a003d8f4dee889/test/integration/basic.js#L55

**Comment by runn1ng** [comment] 2016-10-05 20:29
@jprichardson Why though? When I add it from transaction, it actually calculates the hash.

https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/transaction_builder.js#L334-L338

````javascript
  // is it a Transaction object?
  } else if (txHash instanceof Transaction) {
    prevOutScript = txHash.outs[vout].script
    txHash = txHash.getHash()
  }
````

**Comment by dcousens** [comment] 2016-10-05 23:20
@runn1ng it looks like the `Transaction` which you are providing to `addInput` is causing a `prevOutScript` to be added that isn't supported.
Which is weird.
Can you provide the exact code [or transaction hex and inputs/outputs] for us to play with?

**Comment by runn1ng** [comment] 2016-10-05 23:56
> Can you provide the exact code [and transaction hex and inputs/outputs] for us to play with?

See here

https://github.com/bitcoinjs/bitcoinjs-lib/issues/644#issuecomment-251782056

I have made a correction that should fix it here (together with a fix of another bug - it was testing existence for an array that should not be empty either)

https://github.com/bitcoinjs/bitcoinjs-lib/pull/645

If you catch the actual bug, you can add some test cases for this usage (I have seen in the tests adding  inputs mostly through txids)

**Comment by dcousens** [comment] 2016-10-06 02:25
``` javascript

const bitcoin = require('bitcoin.js');

const privkey = 'cV6Fs4jspcMmUoPXyQSAVkVDfNVjL2Sn8HsBwpDvmKdhF5A9CkQW';
const txhex = '0100000001f7e6430096cd2790bac115aaab22c0a50fb0a1794305302e1a399e81d8d354f4020000006a47304402205793a862d193264afc32713e2e14541e1ff9ebb647dd7e7e6a0051d0faa87de302205216653741ecbbed573ea2fc053209dd6980616701c27be5b958a159fc97f45a012103e877e7deb32d19250dcfe534ea82c99ad739800295cd5429a7f69e2896c36fcdfeffffff0340420f00000000001976a9145c7b8d623fba952d2387703d051d8e931a6aa0a188ac8bda2702000000001976a9145a0ef60784137d03e7868d063b05424f2f43799f88ac40420f00000000001976a9145c7b8d623fba952d2387703d051d8e931a6aa0a188ac2fcc0e00';

const privkeypair = bitcoin.ECPair.fromWIF(privkey, bitcoin.networks.testnet);
const transaction = bitcoin.Transaction.fromHex(txhex);
const builder = new bitcoin.TransactionBuilder(bitcoin.networks.testnet);
builder.addInput(transaction, 0, 0);
builder.addOutput("n4pSwWQZm8Wter1wD6n8RDhEwgCqtQgpcY", 6000);
builder.sign(0, privkeypair); // <- error here
```

The private key here doesn't match the pubKeyHash in that transaction best I can tell.

**Comment by dcousens** [comment] 2016-10-06 02:29
The hashes:
``` javascript
var bitcoinjs = require('bitcoinjs-lib')
var keyPair = bitcoinjs.ECPair.fromWIF('cV6Fs4jspcMmUoPXyQSAVkVDfNVjL2Sn8HsBwpDvmKdhF5A9CkQW', bitcoinjs.networks.testnet)
var hash = bitcoinjs.crypto.hash160(keyPair.getPublicKeyBuffer())

console.log(hash.toString('hex'))
// => 2d7e2fe23c85d57abefe0611b63f1cf768484680
// needs to match 145c7b8d623fba952d2387703d051d8e931a6aa0
```

**Comment by dcousens** [comment] 2016-10-06 02:37
ping @runn1ng are you sure that is the right private key?

**Comment by runn1ng** [comment] 2016-10-06 08:33
Sorry, I was sleeping :)

I confused the private keys. privkey `cQ6483mDWwoG8o4tn6nU9Jg52RKMjPUWXSY1vycAyPRXQJ1Pn2Rq` should be correct. I will edit the comment!

**Comment by dcousens** [comment] 2016-10-06 10:02
Sweet! That resolved it :)
Closing in favour of https://github.com/bitcoinjs/bitcoinjs-lib/pull/647

**Closed by dcousens** 2016-10-06 10:02 UTC
Labels: question
