### ISSUE TITLE
coinbase inputs return "nonstandard" in classifyInputs

### ISSUE THREAD

**Issue by runn1ng** [bitcoinjs/bitcoinjs-lib#845] opened 2017-08-11 14:17 UTC
When I try script.classifyInput on the one input on coinbase transaction, it returns "nonstandard".

I am not sure, if it's a feature or a bug :)

**Comment by dcousens** [comment] 2017-08-12 09:42
@runn1ng a non-feature - not a bug.
PR welcome :+1:

**Comment by afk11** [comment] 2017-08-12 20:51
That's actually a tricky one as I learned recently.. regtest doesn't play well with this, since some fields (block height) aren't required in an earlier blocks coinbase input script, but it will be included later. Some of it is also not enforced by consensus, so can expect some differences I guess.

Not sure the best way to classify that script since it doesn't spend anything (no scriptPubKey) either. The simplest thing is to check txid == [32-bytes of \x00] and vout = 0xffffffff

**Comment by runn1ng** [comment] 2017-08-13 01:43
In classifyscript, you don't have that information. :)

**Comment by afk11** [comment] 2017-08-13 13:23
It's easy for things to fall through the cracks with this practice - classifyInput will return the same result for `[pubkey] CHECKSIGVERIFY TRUE` and `[pubkey] CHECKSIG`, since have the same scriptSig. Coinbase inputs are difficulty (allows freeform text), but it's not even a good idea for regular inputs. 

You could refactor your code so you don't make the assumption that scripts can be classified based on their scriptSig - you should look up the txOut being spent and use classifyOutput on that.

**Comment by runn1ng** [comment] 2017-08-13 13:55
Hm. You need an additional index for that and can't just go through the blockchain for that....

Just for interest - this is a small experiment I did with bitcoinjs-lib and classifying and measuring input lengths - https://gist.github.com/runn1ng/8e2881e5bb44e01748e46b3d1c549038

**Comment by afk11** [comment] 2017-08-13 14:36
Maybe an API of some kind, or bitcoind with txindex=1. Then you can look up any txid and check the outputs script. 

If you see a scriptHash type, you can take the last element of the scriptSig and parse that to learn the scriptType. It'll probably improve the multisig numbers a bit.

**Comment by runn1ng** [comment] 2017-08-13 19:29
It's off topic for this PR by this point :), but I started also classifying the p2sh by types, it's 99% multisig, mostly 2-of-3, I will publish when it is finished

**Comment by runn1ng** [comment] 2017-08-14 00:06
...ok published, again on the same link

**Comment by dcousens** [comment] 2017-08-14 01:14
nice!

**Comment by runn1ng** [comment] 2017-08-14 09:23
Hm, I thought simple gist is enough. :) I don't like medium that much... you are welcome to rewrite/restyle/republish, I won't be angry at you for the karma

**Comment by dcousens** [comment] 2017-08-15 00:49
@runn1ng ha, I didn't mean "medium" the website. 


> I thought simple gist is enough.
It is :+1:

**Closed** 2017-08-23 23:50 UTC
Labels: feature
