### ISSUE TITLE
Bitgo 

### ISSUE THREAD

**Issue by jason0027** [bitcoinjs/bitcoinjs-lib#874] opened 2017-08-30 21:46 UTC
Hi can anyone help to get my coins out of bitgo i have all keys but i cant get my coins looks from another user acc it keep telling me wrong password but all my passwords are correct

**Comment by afk11** [comment] 2017-08-30 22:21
You have opened an issue about this before (https://github.com/bitcoinjs/bitcoinjs-lib/issues/842)

Unfortunately we can't offer support on this, though I suggest you look at the bitgojs library, or implementing whatever is required to derive your private keys.

**Comment by dcousens** [comment] 2017-09-04 19:47
Duplicate of https://github.com/bitcoinjs/bitcoinjs-lib/issues/842

**Closed by dcousens** 2017-09-04 19:47 UTC
Labels: how to / question / docs
